include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    constant_identifier_names: false
    use_setters_to_change_properties: false
    non_constant_identifier_names: false
    avoid_positional_boolean_parameters: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"